version: '3.8'
services:
    db:
        container_name: chope-assment-db
        image: mysql:5.7
        ports:
          - "3306:3306"
        environment:
          MYSQL_DATABASE: chope_assement
          MYSQL_ROOT_PASSWORD: pass123
        restart: always
    
    web:
        container_name: chope-assment-nginx
        image: nginx:1.17
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ./localhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./app:/app
        volumes_from:
            - php
        depends_on:
            - php
        links:
            - php
            
    php:
        container_name: chope-assment-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        expose:
            - "9000"
        depends_on:
            - db
        links:
            - db:mysql
            - redis:redis
        #image: php:7.4-fpm
        volumes:
            - ./app:/app
        env_file: ./app/.env
        working_dir: /app
    
    redis:
        container_name: chope-assment-redis
        image: redis:4.0
        ports:
          - "6379:6379"
        